//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AEUSP : DbContext
    {
        public AEUSP()
            : base("name=AEUSP")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbActivo> tbActivo { get; set; }
        public virtual DbSet<tbActivoGeneral> tbActivoGeneral { get; set; }
        public virtual DbSet<tbAsistente> tbAsistente { get; set; }
        public virtual DbSet<tbBoletaMedica> tbBoletaMedica { get; set; }
        public virtual DbSet<tbColchon> tbColchon { get; set; }
        public virtual DbSet<tbConsumible> tbConsumible { get; set; }
        public virtual DbSet<tbConsumibleAlimentacion> tbConsumibleAlimentacion { get; set; }
        public virtual DbSet<tbConsumibleSalud> tbConsumibleSalud { get; set; }
        public virtual DbSet<tbCuenta> tbCuenta { get; set; }
        public virtual DbSet<tbDetalleMovimientoActivos> tbDetalleMovimientoActivos { get; set; }
        public virtual DbSet<tbEstudiante> tbEstudiante { get; set; }
        public virtual DbSet<tbMovimientoActivo> tbMovimientoActivo { get; set; }
        public virtual DbSet<tbMovimientoAsistencia> tbMovimientoAsistencia { get; set; }
        public virtual DbSet<tbMovimientoCuenta> tbMovimientoCuenta { get; set; }
        public virtual DbSet<tbMovimientoCuentaTracto> tbMovimientoCuentaTracto { get; set; }
        public virtual DbSet<tbOrganismo> tbOrganismo { get; set; }
        public virtual DbSet<tbSuministrosBoleta> tbSuministrosBoleta { get; set; }
        public virtual DbSet<tbUsuario> tbUsuario { get; set; }
        public virtual DbSet<VP_CNS_CEDULAS> VP_CNS_CEDULAS { get; set; }
        public virtual DbSet<VP_CNS_COMISIONES> VP_CNS_COMISIONES { get; set; }
        public virtual DbSet<VP_CNS_NUMEROCOLCHONESDISPONIBLES> VP_CNS_NUMEROCOLCHONESDISPONIBLES { get; set; }
    
        public virtual int SP_ADDUSERORGANISM(string codigo, string miembro)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var miembroParameter = miembro != null ?
                new ObjectParameter("miembro", miembro) :
                new ObjectParameter("miembro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADDUSERORGANISM", codigoParameter, miembroParameter);
        }
    
        public virtual ObjectResult<string> SP_CNS_Asistente(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_CNS_Asistente", cedulaParameter);
        }
    
        public virtual ObjectResult<SP_CNS_ASISTENTEPRESTAMO_Result> SP_CNS_ASISTENTEPRESTAMO(Nullable<int> idMov)
        {
            var idMovParameter = idMov.HasValue ?
                new ObjectParameter("idMov", idMov) :
                new ObjectParameter("idMov", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_ASISTENTEPRESTAMO_Result>("SP_CNS_ASISTENTEPRESTAMO", idMovParameter);
        }
    
        public virtual ObjectResult<SP_CNS_COLCHONES_Result> SP_CNS_COLCHONES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_COLCHONES_Result>("SP_CNS_COLCHONES");
        }
    
        public virtual ObjectResult<SP_CNS_COLCHONESPRESTAMO_Result> SP_CNS_COLCHONESPRESTAMO(Nullable<int> idMov)
        {
            var idMovParameter = idMov.HasValue ?
                new ObjectParameter("idMov", idMov) :
                new ObjectParameter("idMov", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_COLCHONESPRESTAMO_Result>("SP_CNS_COLCHONESPRESTAMO", idMovParameter);
        }
    
        public virtual ObjectResult<SP_CNS_COLCHONPORNUMERO_Result> SP_CNS_COLCHONPORNUMERO(Nullable<int> numero)
        {
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_COLCHONPORNUMERO_Result>("SP_CNS_COLCHONPORNUMERO", numeroParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CNS_COLCHONXNUMERO(Nullable<int> numero)
        {
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CNS_COLCHONXNUMERO", numeroParameter);
        }
    
        public virtual ObjectResult<Sp_Cns_ConsumiblesLimpiezaPorNombre_Result> Sp_Cns_ConsumiblesLimpiezaPorNombre(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Cns_ConsumiblesLimpiezaPorNombre_Result>("Sp_Cns_ConsumiblesLimpiezaPorNombre", nombreParameter);
        }
    
        public virtual ObjectResult<SP_CNS_DISPONIBILIDADCOLCHONES_Result> SP_CNS_DISPONIBILIDADCOLCHONES(Nullable<int> disponibilidad)
        {
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("disponibilidad", disponibilidad) :
                new ObjectParameter("disponibilidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_DISPONIBILIDADCOLCHONES_Result>("SP_CNS_DISPONIBILIDADCOLCHONES", disponibilidadParameter);
        }
    
        public virtual ObjectResult<Sp_Cns_EntradasActivas_Result> Sp_Cns_EntradasActivas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Cns_EntradasActivas_Result>("Sp_Cns_EntradasActivas");
        }
    
        public virtual ObjectResult<Sp_Cns_EntradasPorFecha_Result> Sp_Cns_EntradasPorFecha(string movimiento, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaSalida)
        {
            var movimientoParameter = movimiento != null ?
                new ObjectParameter("movimiento", movimiento) :
                new ObjectParameter("movimiento", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("fechaSalida", fechaSalida) :
                new ObjectParameter("fechaSalida", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Cns_EntradasPorFecha_Result>("Sp_Cns_EntradasPorFecha", movimientoParameter, fechaInicioParameter, fechaSalidaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CNS_IDCOLCHON(Nullable<int> numColchon)
        {
            var numColchonParameter = numColchon.HasValue ?
                new ObjectParameter("numColchon", numColchon) :
                new ObjectParameter("numColchon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CNS_IDCOLCHON", numColchonParameter);
        }
    
        public virtual ObjectResult<Sp_Cns_InvaAsoPorNombre_Result> Sp_Cns_InvaAsoPorNombre(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Cns_InvaAsoPorNombre_Result>("Sp_Cns_InvaAsoPorNombre", nombreParameter);
        }
    
        public virtual ObjectResult<Sp_Cns_InvActivosAso_Result> Sp_Cns_InvActivosAso()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Cns_InvActivosAso_Result>("Sp_Cns_InvActivosAso");
        }
    
        public virtual ObjectResult<SP_CNS_MOVIMIENTOSEFECTIVOXFECHA_Result> SP_CNS_MOVIMIENTOSEFECTIVOXFECHA(Nullable<System.DateTime> fechaI, Nullable<System.DateTime> fechaF)
        {
            var fechaIParameter = fechaI.HasValue ?
                new ObjectParameter("fechaI", fechaI) :
                new ObjectParameter("fechaI", typeof(System.DateTime));
    
            var fechaFParameter = fechaF.HasValue ?
                new ObjectParameter("fechaF", fechaF) :
                new ObjectParameter("fechaF", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_MOVIMIENTOSEFECTIVOXFECHA_Result>("SP_CNS_MOVIMIENTOSEFECTIVOXFECHA", fechaIParameter, fechaFParameter);
        }
    
        public virtual ObjectResult<SP_CNS_MOVIMIENTOSTRACTOXFECHA_Result> SP_CNS_MOVIMIENTOSTRACTOXFECHA(Nullable<System.DateTime> fechaI, Nullable<System.DateTime> fechaF)
        {
            var fechaIParameter = fechaI.HasValue ?
                new ObjectParameter("fechaI", fechaI) :
                new ObjectParameter("fechaI", typeof(System.DateTime));
    
            var fechaFParameter = fechaF.HasValue ?
                new ObjectParameter("fechaF", fechaF) :
                new ObjectParameter("fechaF", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_MOVIMIENTOSTRACTOXFECHA_Result>("SP_CNS_MOVIMIENTOSTRACTOXFECHA", fechaIParameter, fechaFParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CNS_MOVTRACTO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CNS_MOVTRACTO");
        }
    
        public virtual ObjectResult<string> SP_CNS_ORGANISMOUSUARIO(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_CNS_ORGANISMOUSUARIO", usuarioParameter);
        }
    
        public virtual ObjectResult<SP_CNS_PRESTAMOCOLCHONESXNUMERO_Result> SP_CNS_PRESTAMOCOLCHONESXNUMERO(string numero)
        {
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_PRESTAMOCOLCHONESXNUMERO_Result>("SP_CNS_PRESTAMOCOLCHONESXNUMERO", numeroParameter);
        }
    
        public virtual ObjectResult<SP_CNS_PRESTAMOSCOLCHONESXCEDULA_Result> SP_CNS_PRESTAMOSCOLCHONESXCEDULA(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_PRESTAMOSCOLCHONESXCEDULA_Result>("SP_CNS_PRESTAMOSCOLCHONESXCEDULA", cedulaParameter);
        }
    
        public virtual ObjectResult<SP_CNS_USUARIOS_Result> SP_CNS_USUARIOS(string carnet)
        {
            var carnetParameter = carnet != null ?
                new ObjectParameter("carnet", carnet) :
                new ObjectParameter("carnet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_USUARIOS_Result>("SP_CNS_USUARIOS", carnetParameter);
        }
    
        public virtual int SP_DTL_ELIMINARDETALLECOLCHO(Nullable<int> idAct)
        {
            var idActParameter = idAct.HasValue ?
                new ObjectParameter("idAct", idAct) :
                new ObjectParameter("idAct", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DTL_ELIMINARDETALLECOLCHO", idActParameter);
        }
    
        public virtual int Sp_Ins_Movimiento(string cedula, string accion, Nullable<System.DateTime> fecha)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Ins_Movimiento", cedulaParameter, accionParameter, fechaParameter);
        }
    
        public virtual int SP_INS_REGISTRARCOLCHON(string estado, string observacion, Nullable<int> numColchon, string procedencia)
        {
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("observacion", observacion) :
                new ObjectParameter("observacion", typeof(string));
    
            var numColchonParameter = numColchon.HasValue ?
                new ObjectParameter("numColchon", numColchon) :
                new ObjectParameter("numColchon", typeof(int));
    
            var procedenciaParameter = procedencia != null ?
                new ObjectParameter("procedencia", procedencia) :
                new ObjectParameter("procedencia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_REGISTRARCOLCHON", estadoParameter, observacionParameter, numColchonParameter, procedenciaParameter);
        }
    
        public virtual int SP_INS_REGISTRARDEVOLUCIONESCOLCHON(Nullable<int> idActivo, Nullable<int> cantidad)
        {
            var idActivoParameter = idActivo.HasValue ?
                new ObjectParameter("idActivo", idActivo) :
                new ObjectParameter("idActivo", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_REGISTRARDEVOLUCIONESCOLCHON", idActivoParameter, cantidadParameter);
        }
    
        public virtual int SP_INS_REGISTRARMOVIMIENTO(string carnet, string cedula, string tipo, Nullable<System.DateTime> fecha)
        {
            var carnetParameter = carnet != null ?
                new ObjectParameter("carnet", carnet) :
                new ObjectParameter("carnet", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_REGISTRARMOVIMIENTO", carnetParameter, cedulaParameter, tipoParameter, fechaParameter);
        }
    
        public virtual int SP_INS_REGISTRARPRESTAMOSCOLCHON(Nullable<int> idActivo, Nullable<int> cantidad, string ubicacion)
        {
            var idActivoParameter = idActivo.HasValue ?
                new ObjectParameter("idActivo", idActivo) :
                new ObjectParameter("idActivo", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var ubicacionParameter = ubicacion != null ?
                new ObjectParameter("ubicacion", ubicacion) :
                new ObjectParameter("ubicacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_REGISTRARPRESTAMOSCOLCHON", idActivoParameter, cantidadParameter, ubicacionParameter);
        }
    
        public virtual int SP_ISN_CUENTA(string idCuent, string carnetU, string detalle, Nullable<System.DateTime> fecha, string tipo, Nullable<decimal> monto)
        {
            var idCuentParameter = idCuent != null ?
                new ObjectParameter("idCuent", idCuent) :
                new ObjectParameter("idCuent", typeof(string));
    
            var carnetUParameter = carnetU != null ?
                new ObjectParameter("carnetU", carnetU) :
                new ObjectParameter("carnetU", typeof(string));
    
            var detalleParameter = detalle != null ?
                new ObjectParameter("detalle", detalle) :
                new ObjectParameter("detalle", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("monto", monto) :
                new ObjectParameter("monto", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ISN_CUENTA", idCuentParameter, carnetUParameter, detalleParameter, fechaParameter, tipoParameter, montoParameter);
        }
    
        public virtual int SP_ISN_TRACTO(Nullable<int> idMov, string factura, string empresa)
        {
            var idMovParameter = idMov.HasValue ?
                new ObjectParameter("idMov", idMov) :
                new ObjectParameter("idMov", typeof(int));
    
            var facturaParameter = factura != null ?
                new ObjectParameter("factura", factura) :
                new ObjectParameter("factura", typeof(string));
    
            var empresaParameter = empresa != null ?
                new ObjectParameter("empresa", empresa) :
                new ObjectParameter("empresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ISN_TRACTO", idMovParameter, facturaParameter, empresaParameter);
        }
    
        public virtual ObjectResult<string> SP_OBT_ORGANISMO(string carnet)
        {
            var carnetParameter = carnet != null ?
                new ObjectParameter("carnet", carnet) :
                new ObjectParameter("carnet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_OBT_ORGANISMO", carnetParameter);
        }
    
        public virtual ObjectResult<Sp_Cns_FiltroCategoria_Result> Sp_Cns_FiltroCategoria(string filtro)
        {
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Cns_FiltroCategoria_Result>("Sp_Cns_FiltroCategoria", filtroParameter);
        }
    
        public virtual ObjectResult<Sp_Cns_FiltroAlimentacion_Result> Sp_Cns_FiltroAlimentacion(string filtro)
        {
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Cns_FiltroAlimentacion_Result>("Sp_Cns_FiltroAlimentacion", filtroParameter);
        }
    
        public virtual int SP_ELIMINAR_USUARIO(string carnet)
        {
            var carnetParameter = carnet != null ?
                new ObjectParameter("carnet", carnet) :
                new ObjectParameter("carnet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINAR_USUARIO", carnetParameter);
        }
    }
}
