//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbActivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbActivo()
        {
            this.tbActivoGeneral = new HashSet<tbActivoGeneral>();
            this.tbColchon = new HashSet<tbColchon>();
            this.tbDetalleMovimientoActivos = new HashSet<tbDetalleMovimientoActivos>();
        }
    
        public int idActivo { get; set; }
        public string codigoOrganismo { get; set; }
        public int cantidadTotal { get; set; }
        public int cantidadInventario { get; set; }
        public string estado { get; set; }
        public string observacion { get; set; }
    
        public virtual tbOrganismo tbOrganismo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbActivoGeneral> tbActivoGeneral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbColchon> tbColchon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetalleMovimientoActivos> tbDetalleMovimientoActivos { get; set; }
    }
}
