//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMovimientoCuenta
    {
        public int idMovimiento { get; set; }
        public string idCuenta { get; set; }
        public string carnetUsuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string detalle { get; set; }
        public string tipo { get; set; }
        public Nullable<decimal> monto { get; set; }
    
        public virtual tbCuenta tbCuenta { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbMovimientoCuentaTracto tbMovimientoCuentaTracto { get; set; }
    }
}
