//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMovimientoActivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbMovimientoActivo()
        {
            this.tbDetalleMovimientoActivos = new HashSet<tbDetalleMovimientoActivos>();
        }
    
        public int idMovimiento { get; set; }
        public string carnetUsuario { get; set; }
        public string cedulaAsistente { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipo { get; set; }
    
        public virtual tbAsistente tbAsistente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetalleMovimientoActivos> tbDetalleMovimientoActivos { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
