//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSuministrosBoleta
    {
        public int numeroBoleta { get; set; }
        public int codigo { get; set; }
        public int cantidad { get; set; }
    
        public virtual tbBoletaMedica tbBoletaMedica { get; set; }
        public virtual tbConsumibleSalud tbConsumibleSalud { get; set; }
    }
}
